import { Product } from '@/types/database';

export const FALLBACK_DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-01-black-shirt',
    name: 'Retro Black Graphic Shirt',
    category: 'shirts',
    price: 1490,
    description: 'Модерна машка кошула со впечатлива графика и релаксиран крој. 100% удобен памучен материјал, совршена за вечерни и урбани секојдневни комбинации.',
    image_url: '/assets/01_black_graphic_shirt.jpg',
    additional_images: ['/assets/07_black_graphic_tshirt.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T20:00:00.000Z',
    updated_at: '2026-08-18T20:00:00.000Z',
    variants: [
      { id: 'v-bs-s', product_id: 'prod-01-black-shirt', size: 'S', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-bs-m', product_id: 'prod-01-black-shirt', size: 'M', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-bs-l', product_id: 'prod-01-black-shirt', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-bs-xl', product_id: 'prod-01-black-shirt', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-bs-xxl', product_id: 'prod-01-black-shirt', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-01-varsity-black',
    name: 'Varsity Baseball Jacket Black/White',
    category: 'other',
    price: 2690,
    description: 'Класична колеџ јакна со црно-бел контраст, квалитетни метални копчиња и мека памучна постава. Автентичен American varsity стил.',
    image_url: '/assets/01_white_black_varsity_jacket.jpg',
    additional_images: ['/assets/04_red_white_bulls_varsity.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T19:00:00.000Z',
    updated_at: '2026-08-18T19:00:00.000Z',
    variants: [
      { id: 'v-vb-m', product_id: 'prod-01-varsity-black', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-vb-l', product_id: 'prod-01-varsity-black', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-vb-xl', product_id: 'prod-01-varsity-black', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-vb-xxl', product_id: 'prod-01-varsity-black', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-09-charcoal-jeans',
    name: 'Charcoal Distressed Slim Jeans',
    category: 'jeans',
    price: 1990,
    description: 'Премиум машки фармерки во темно-сива (charcoal) нијанса со модерен slim-fit крој, суптилни модни оштетувања и 2% еластин за максимална удобност.',
    image_url: '/assets/09_charcoal_distressed_jeans.jpg',
    additional_images: ['/assets/look-01.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T18:00:00.000Z',
    updated_at: '2026-08-18T18:00:00.000Z',
    variants: [
      { id: 'v-cj-30', product_id: 'prod-09-charcoal-jeans', size: '30', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-cj-31', product_id: 'prod-09-charcoal-jeans', size: '31', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-cj-32', product_id: 'prod-09-charcoal-jeans', size: '32', stock_quantity: 5, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-cj-33', product_id: 'prod-09-charcoal-jeans', size: '33', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-cj-34', product_id: 'prod-09-charcoal-jeans', size: '34', stock_quantity: 4, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
      { id: 'v-cj-36', product_id: 'prod-09-charcoal-jeans', size: '36', stock_quantity: 2, reserved_quantity: 0, display_order: 6, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-04-bulls-varsity',
    name: 'Bulls Red Varsity Jacket',
    category: 'other',
    price: 2790,
    description: 'Впечатлива црвено-бела колеџ јакна со Bulls везени апликации, ластици на ракавите и удобен спортски крој.',
    image_url: '/assets/04_red_white_bulls_varsity.jpg',
    additional_images: ['/assets/01_white_black_varsity_jacket.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T17:00:00.000Z',
    updated_at: '2026-08-18T17:00:00.000Z',
    variants: [
      { id: 'v-bv-m', product_id: 'prod-04-bulls-varsity', size: 'M', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-bv-l', product_id: 'prod-04-bulls-varsity', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-bv-xl', product_id: 'prod-04-bulls-varsity', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-bv-xxl', product_id: 'prod-04-bulls-varsity', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-05-green-hoodie',
    name: 'Forest Green Graphic Hoodie',
    category: 'sweaters',
    price: 1890,
    description: 'Топол машки дуксер во темнозелена нијанса со автентичен урбан принт, длабока качулка и преден кенгур џеб.',
    image_url: '/assets/05_green_escobar_hoodie.jpg',
    additional_images: ['/assets/10_grey_graphic_hoodie.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T16:00:00.000Z',
    updated_at: '2026-08-18T16:00:00.000Z',
    variants: [
      { id: 'v-gh-s', product_id: 'prod-05-green-hoodie', size: 'S', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-gh-m', product_id: 'prod-05-green-hoodie', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-gh-l', product_id: 'prod-05-green-hoodie', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-gh-xl', product_id: 'prod-05-green-hoodie', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-gh-xxl', product_id: 'prod-05-green-hoodie', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-08-green-puffer',
    name: 'Olive Green Puffer Jacket',
    category: 'other',
    price: 3290,
    description: 'Машка пуфер јакна со термичка изолација во маслинесто зелена боја. Лесна, удобна и отпорна на ветер и влага.',
    image_url: '/assets/08_green_puffer_jacket.jpg',
    additional_images: ['/assets/02_white_zip_jacket.jpg'],
    active: true,
    is_new: true,
    created_at: '2026-08-18T15:00:00.000Z',
    updated_at: '2026-08-18T15:00:00.000Z',
    variants: [
      { id: 'v-gp-m', product_id: 'prod-08-green-puffer', size: 'M', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-gp-l', product_id: 'prod-08-green-puffer', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-gp-xl', product_id: 'prod-08-green-puffer', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-gp-xxl', product_id: 'prod-08-green-puffer', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-07-champions-sweater',
    name: 'Champions Colorblock Sweater',
    category: 'sweaters',
    price: 1690,
    description: 'Колорблок плетен џемпер со ретро спортски шмек. Одлична комбинација на темно сина, бела и црвена нијанса.',
    image_url: '/assets/07_champions_colorblock_sweater.jpg',
    additional_images: ['/assets/06_light_blue_graphic_sweater.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T12:00:00.000Z',
    updated_at: '2026-08-17T12:00:00.000Z',
    variants: [
      { id: 'v-cs-s', product_id: 'prod-07-champions-sweater', size: 'S', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-cs-m', product_id: 'prod-07-champions-sweater', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-cs-l', product_id: 'prod-07-champions-sweater', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-cs-xl', product_id: 'prod-07-champions-sweater', size: 'XL', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-02-white-tshirt',
    name: 'White Urban Graphic Tee',
    category: 'shirts',
    price: 890,
    description: 'Класична бела маица од 100% органски памук со минимален урбан принт. Совршена основа за секој стил.',
    image_url: '/assets/02_white_graphic_tshirt.jpg',
    additional_images: ['/assets/03_white_graphic_tshirt_alt.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T11:00:00.000Z',
    updated_at: '2026-08-17T11:00:00.000Z',
    variants: [
      { id: 'v-wt-s', product_id: 'prod-02-white-tshirt', size: 'S', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-wt-m', product_id: 'prod-02-white-tshirt', size: 'M', stock_quantity: 5, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-wt-l', product_id: 'prod-02-white-tshirt', size: 'L', stock_quantity: 5, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-wt-xl', product_id: 'prod-02-white-tshirt', size: 'XL', stock_quantity: 4, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-wt-xxl', product_id: 'prod-02-white-tshirt', size: 'XXL', stock_quantity: 2, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-10-grey-hoodie',
    name: 'Heather Grey Street Hoodie',
    category: 'sweaters',
    price: 1890,
    description: 'Машки меланж сив дуксер со качулка. Густ памук со термо постава за ладни денови.',
    image_url: '/assets/10_grey_graphic_hoodie.jpg',
    additional_images: ['/assets/05_green_escobar_hoodie.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T10:00:00.000Z',
    updated_at: '2026-08-17T10:00:00.000Z',
    variants: [
      { id: 'v-gh2-s', product_id: 'prod-10-grey-hoodie', size: 'S', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-gh2-m', product_id: 'prod-10-grey-hoodie', size: 'M', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-gh2-l', product_id: 'prod-10-grey-hoodie', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-gh2-xl', product_id: 'prod-10-grey-hoodie', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-06-blue-sweater',
    name: 'Sky Blue Crewneck Sweater',
    category: 'sweaters',
    price: 1590,
    description: 'Светлосин лесен плетен џемпер со округол израз. Елегантен и удобен избор за работа и прошетка.',
    image_url: '/assets/06_light_blue_graphic_sweater.jpg',
    additional_images: ['/assets/09_mint_graphic_sweater_back.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T09:00:00.000Z',
    updated_at: '2026-08-17T09:00:00.000Z',
    variants: [
      { id: 'v-sbs-m', product_id: 'prod-06-blue-sweater', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-sbs-l', product_id: 'prod-06-blue-sweater', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-sbs-xl', product_id: 'prod-06-blue-sweater', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-03-blue-jacket',
    name: 'Royal Blue Graphic Bomber',
    category: 'other',
    price: 2490,
    description: 'Бомбер јакна во кралско сина боја со впечатлив мотив на грбот и висококвалитетни патенти.',
    image_url: '/assets/03_blue_graphic_jacket_back.jpg',
    additional_images: ['/assets/01_white_black_varsity_jacket.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T08:00:00.000Z',
    updated_at: '2026-08-17T08:00:00.000Z',
    variants: [
      { id: 'v-rbj-m', product_id: 'prod-03-blue-jacket', size: 'M', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-rbj-l', product_id: 'prod-03-blue-jacket', size: 'L', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-rbj-xl', product_id: 'prod-03-blue-jacket', size: 'XL', stock_quantity: 2, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'prod-08-lucky-beige',
    name: 'Lucky 24 Beige Oversize Tee',
    category: 'shirts',
    price: 890,
    description: 'Беж oversize машка маица со спортски принт Lucky 24. Мека памучна текстура со современ крој.',
    image_url: '/assets/08_lucky_24_beige_tshirt.jpg',
    additional_images: ['/assets/04_dusty_rose_tshirt.jpg'],
    active: true,
    is_new: false,
    created_at: '2026-08-17T07:00:00.000Z',
    updated_at: '2026-08-17T07:00:00.000Z',
    variants: [
      { id: 'v-lb-s', product_id: 'prod-08-lucky-beige', size: 'S', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-lb-m', product_id: 'prod-08-lucky-beige', size: 'M', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-lb-l', product_id: 'prod-08-lucky-beige', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-lb-xl', product_id: 'prod-08-lucky-beige', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
];
