import { Product } from '@/types/database';

export const FALLBACK_DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-jeans-01',
    name: 'Retro Slim Jeans 01',
    category: 'jeans',
    price: 1890,
    description: 'Премиум slim fit фармерки од еластичен памук. Совршен крој за секојдневна комбинација.',
    image_url: '/assets/look-01.jpg',
    additional_images: ['/assets/store-01.jpg'],
    active: true,
    is_new: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-j1-30', product_id: 'demo-jeans-01', size: '30', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-j1-31', product_id: 'demo-jeans-01', size: '31', stock_quantity: 2, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-j1-32', product_id: 'demo-jeans-01', size: '32', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-j1-33', product_id: 'demo-jeans-01', size: '33', stock_quantity: 1, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-j1-34', product_id: 'demo-jeans-01', size: '34', stock_quantity: 3, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
      { id: 'v-j1-36', product_id: 'demo-jeans-01', size: '36', stock_quantity: 2, reserved_quantity: 0, display_order: 6, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'demo-sweater-01',
    name: 'Casual Knit Sweater Black',
    category: 'sweaters',
    price: 1490,
    description: 'Класичен црн плетен џемпер. Мек и топол материјал, идеален за слоевити комбинации.',
    image_url: '/assets/store-02.jpg',
    additional_images: ['/assets/look-01.jpg'],
    active: true,
    is_new: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-sw1-s', product_id: 'demo-sweater-01', size: 'S', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-sw1-m', product_id: 'demo-sweater-01', size: 'M', stock_quantity: 5, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-sw1-l', product_id: 'demo-sweater-01', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-sw1-xl', product_id: 'demo-sweater-01', size: 'XL', stock_quantity: 3, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
      { id: 'v-sw1-xxl', product_id: 'demo-sweater-01', size: 'XXL', stock_quantity: 1, reserved_quantity: 0, display_order: 5, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'demo-shirt-01',
    name: 'Classic Oxford Shirt',
    category: 'shirts',
    price: 1290,
    description: 'Памучна кошула со модерен структуриран крој. Погодна и за лежерен и за полу-елегантен стил.',
    image_url: '/assets/look-02.jpg',
    additional_images: ['/assets/store-02.jpg'],
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-sh1-m', product_id: 'demo-shirt-01', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-sh1-l', product_id: 'demo-shirt-01', size: 'L', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-sh1-xl', product_id: 'demo-shirt-01', size: 'XL', stock_quantity: 2, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'demo-trousers-01',
    name: 'Casual Chino Trousers',
    category: 'trousers',
    price: 1790,
    description: 'Удобни чино панталони со модерен крој. Квалитетен материјал што лесно се комбинира со кошули и џемпери.',
    image_url: '/assets/store-01.jpg',
    additional_images: ['/assets/look-02.jpg'],
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-tr1-30', product_id: 'demo-trousers-01', size: '30', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-tr1-32', product_id: 'demo-trousers-01', size: '32', stock_quantity: 4, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-tr1-34', product_id: 'demo-trousers-01', size: '34', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-tr1-36', product_id: 'demo-trousers-01', size: '36', stock_quantity: 1, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'demo-jeans-02',
    name: 'Retro Vintage Wash Jeans',
    category: 'jeans',
    price: 1990,
    description: 'Класични фармерки со vintage wash нијанса. Издржлив тексас со одлична удобност при носење.',
    image_url: '/assets/store-02.jpg',
    additional_images: ['/assets/store-01.jpg'],
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-j2-30', product_id: 'demo-jeans-02', size: '30', stock_quantity: 2, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-j2-32', product_id: 'demo-jeans-02', size: '32', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-j2-34', product_id: 'demo-jeans-02', size: '34', stock_quantity: 4, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-j2-36', product_id: 'demo-jeans-02', size: '36', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
  {
    id: 'demo-sweater-02',
    name: 'Everyday Crewneck Knit',
    category: 'sweaters',
    price: 1590,
    description: 'Елегантен crewneck плетен џемпер во неутрална боја. Лесен за носење врз кошула или маица.',
    image_url: '/assets/look-01.jpg',
    additional_images: ['/assets/look-02.jpg'],
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    variants: [
      { id: 'v-sw2-s', product_id: 'demo-sweater-02', size: 'S', stock_quantity: 1, reserved_quantity: 0, display_order: 1, created_at: '', updated_at: '' },
      { id: 'v-sw2-m', product_id: 'demo-sweater-02', size: 'M', stock_quantity: 3, reserved_quantity: 0, display_order: 2, created_at: '', updated_at: '' },
      { id: 'v-sw2-l', product_id: 'demo-sweater-02', size: 'L', stock_quantity: 3, reserved_quantity: 0, display_order: 3, created_at: '', updated_at: '' },
      { id: 'v-sw2-xl', product_id: 'demo-sweater-02', size: 'XL', stock_quantity: 2, reserved_quantity: 0, display_order: 4, created_at: '', updated_at: '' },
    ],
  },
];
